<?php
/** Premium batch operations tests. @package LaqiUnitStockManager */
use LaqiUnitStockManager\Container;
use LaqiUnitStockManager\Domain\Quantity;
use LaqiUnitStockManager\Premium\Batches\BatchAllocationRepository;
use LaqiUnitStockManager\Premium\Batches\BatchOperationsService;
use LaqiUnitStockManager\Premium\Batches\BatchRepository;
use LaqiUnitStockManager\Premium\Reservations\ReservationRepository;
use LaqiUnitStockManager\Premium\Supply\StockHoldRepository;
use LaqiUnitStockManager\Storage\Schema;
/** Verifies batch state and count operations preserve the pool ledger invariant. */
class Test_Batch_Operations extends WP_UnitTestCase {
	/** @var int */ private $pool_id; /** @var int */ private $batch_id; /** @var BatchRepository */ private $batches; /** @var BatchOperationsService */ private $operations;
	/** Fixture. */ public function set_up():void{parent::set_up();global $wpdb;$container=new Container();$this->batches=new BatchRepository($wpdb);$this->batches->install();(new BatchAllocationRepository($wpdb))->install();$mutations=$container->stock_mutation_service();$this->operations=new BatchOperationsService($this->batches,$mutations);$key=wp_generate_uuid4();$this->pool_id=$container->pool_repository()->create('Batch operations '.$key,new Quantity('count',0),'each','each')->id();$movement=$mutations->apply($this->pool_id,10,'supplier_receipt','batch-operations:'.$key);$this->batch_id=$this->batches->record_receipt($this->pool_id,0,$movement->movement_id(),10,'OPS','2028-01-01');}
	/** Cleanup. */ public function tear_down():void{global $wpdb;$wpdb->delete(Schema::table('reservations'),array('pool_id'=>$this->pool_id),array('%d'));$wpdb->delete(Schema::table('stock_holds'),array('pool_id'=>$this->pool_id),array('%d'));$wpdb->delete(Schema::table('batch_events'),array('batch_id'=>$this->batch_id),array('%d'));$wpdb->delete(Schema::table('batch_allocations'),array('pool_id'=>$this->pool_id),array('%d'));$wpdb->delete(Schema::table('batches'),array('pool_id'=>$this->pool_id),array('%d'));$wpdb->delete(Schema::table('movements'),array('pool_id'=>$this->pool_id),array('%d'));$wpdb->delete(Schema::table('pools'),array('id'=>$this->pool_id),array('%d'));parent::tear_down();}
	/** Quarantine changes ATS but not physical on-hand, and release restores ATS with history. */ public function test_quarantine_and_release_lifecycle():void{$this->operations->quarantine($this->batch_id,7,'Quality review');$this->assertSame(10,$this->balance());$this->assertSame(0,apply_filters('laqi_lusm_pool_available_quantity',10,$this->pool_id));$this->assertSame('quarantined',$this->batches->find($this->batch_id)['status']);$this->operations->release($this->batch_id,8,'Review passed');$this->assertSame(10,apply_filters('laqi_lusm_pool_available_quantity',10,$this->pool_id));$this->assertSame('active',$this->batches->find($this->batch_id)['status']);$events=$this->batches->events($this->batch_id);$this->assertSame(array('quarantine','release'),wp_list_pluck($events,'event_type'));$this->assertSame('7',$events[0]['actor_id']);$this->assertSame('Quality review',$events[0]['reason']);}
	/** Write-off targets this batch and changes pool and batch exactly once. */ public function test_write_off_is_exact_and_idempotent():void{$this->operations->quarantine($this->batch_id);$this->operations->write_off($this->batch_id,7);$this->operations->write_off($this->batch_id,7);$batch=$this->batches->find($this->batch_id);$this->assertSame(0,$this->balance());$this->assertSame(0,(int)$batch['quantity_available_base']);$this->assertSame('depleted',$batch['status']);}
	/** Stocktake reconciles both layers through one movement for decreases and increases. */ public function test_stocktake_reconciles_batch_and_pool():void{$this->operations->stocktake($this->batch_id,7,7);$this->assertSame(7,$this->balance());$this->assertSame(7,(int)$this->batches->find($this->batch_id)['quantity_available_base']);$this->operations->stocktake($this->batch_id,9,7);$this->assertSame(9,$this->balance());$this->assertSame(9,(int)$this->batches->find($this->batch_id)['quantity_available_base']);}
	/** Reservation locking cannot consume quarantined batch supply. */ public function test_reservations_reject_quarantined_supply():void{global $wpdb;$this->operations->quarantine($this->batch_id);$this->expectException(RuntimeException::class);(new ReservationRepository($wpdb))->reserve(910001,array($this->pool_id=>1),gmdate('Y-m-d H:i:s',time()+HOUR_IN_SECONDS));}
	/** Hold locking cannot consume quarantined batch supply. */ public function test_holds_reject_quarantined_supply():void{global $wpdb;$this->operations->quarantine($this->batch_id);$this->expectException(InvalidArgumentException::class);(new StockHoldRepository($wpdb))->place($this->pool_id,'damaged',1,'Unavailable',7);}
	/** Pool balance. */ private function balance():int{global $wpdb;return(int)$wpdb->get_var($wpdb->prepare('SELECT quantity_base FROM '.Schema::table('pools').' WHERE id=%d',$this->pool_id));}
}
