<?php
/** Premium atomic batch transfer tests. @package LaqiUnitStockManager */

use LaqiUnitStockManager\Container;
use LaqiUnitStockManager\Domain\Quantity;
use LaqiUnitStockManager\Premium\Batches\BatchOperationsService;
use LaqiUnitStockManager\Premium\Batches\BatchRepository;
use LaqiUnitStockManager\Premium\Batches\BatchTransferService;
use LaqiUnitStockManager\Storage\Schema;

/** Verifies transfer movements and destination lots commit as one operation. */
class Test_Batch_Transfers extends WP_UnitTestCase {
	/** @var int */ private $source_pool; /** @var int */ private $destination_pool; /** @var int */ private $batch_id; /** @var BatchRepository */ private $batches; /** @var BatchTransferService */ private $transfers;
	/** Fixture. */ public function set_up():void{parent::set_up();global $wpdb;$container=new Container();$pools=$container->pool_repository();$mutations=$container->stock_mutation_service();$this->batches=new BatchRepository($wpdb);$this->source_pool=$pools->create('Transfer source '.wp_generate_uuid4(),new Quantity('count',0),'each','each')->id();$this->destination_pool=$pools->create('Transfer destination '.wp_generate_uuid4(),new Quantity('count',0),'each','each')->id();$movement=$mutations->apply($this->source_pool,10,'supplier_receipt','transfer-receipt:'.wp_generate_uuid4());$this->batch_id=$this->batches->record_receipt($this->source_pool,0,$movement->movement_id(),10,'LOT-T','2028-06-01',100,'EUR');$this->transfers=new BatchTransferService($this->batches,$pools,$mutations);}
	/** Cleanup. */ public function tear_down():void{global $wpdb;$batch_ids=$wpdb->get_col($wpdb->prepare('SELECT id FROM '.Schema::table('batches').' WHERE pool_id IN (%d,%d)',$this->source_pool,$this->destination_pool));foreach($batch_ids as $batch_id){$wpdb->delete(Schema::table('batch_events'),array('batch_id'=>(int)$batch_id),array('%d'));}$wpdb->query($wpdb->prepare('DELETE FROM '.Schema::table('batch_allocations').' WHERE pool_id IN (%d,%d)',$this->source_pool,$this->destination_pool));$wpdb->query($wpdb->prepare('DELETE FROM '.Schema::table('batches').' WHERE pool_id IN (%d,%d)',$this->source_pool,$this->destination_pool));$wpdb->query($wpdb->prepare('DELETE FROM '.Schema::table('movements').' WHERE pool_id IN (%d,%d)',$this->source_pool,$this->destination_pool));$wpdb->query($wpdb->prepare('DELETE FROM '.Schema::table('pools').' WHERE id IN (%d,%d)',$this->source_pool,$this->destination_pool));parent::tear_down();}
	/** Exact quantity, lot identity, expiry, lineage, and proportional cost move once. */ public function test_transfer_is_atomic_and_idempotent():void{$key='batch-transfer:'.wp_generate_uuid4();$this->transfers->transfer($this->batch_id,$this->destination_pool,4,7,'Move to packing room',$key);$this->transfers->transfer($this->batch_id,$this->destination_pool,4,7,'Move to packing room',$key);$this->assertSame(6,$this->pool_balance($this->source_pool));$this->assertSame(4,$this->pool_balance($this->destination_pool));$this->assertSame(6,(int)$this->batches->find($this->batch_id)['quantity_available_base']);$destination=$this->destination_batch();$this->assertSame($this->batch_id,(int)$destination['source_batch_id']);$this->assertSame('LOT-T',$destination['supplier_lot']);$this->assertSame('2028-06-01',$destination['expiry_date']);$this->assertSame(4,(int)$destination['quantity_available_base']);$this->assertSame(40,(int)$destination['total_cost_minor']);$this->assertSame('EUR',$destination['currency']);}
	/** A failed extension rolls back both pools and both batch effects. */ public function test_failure_rolls_back_entire_transfer():void{$failure=static function(int $pool_id,int $delta,string $type):void{unset($pool_id,$delta);if('batch_transfer_in'===$type){throw new RuntimeException('Simulated transfer failure.');}};add_action('laqi_lusm_stock_movement_applied',$failure,20,3);try{$this->transfers->transfer($this->batch_id,$this->destination_pool,4,7,'Fail safely','batch-transfer:'.wp_generate_uuid4());$this->fail('Expected transfer failure.');}catch(RuntimeException $error){$this->assertSame('Simulated transfer failure.',$error->getMessage());}finally{remove_action('laqi_lusm_stock_movement_applied',$failure,20);}$this->assertSame(10,$this->pool_balance($this->source_pool));$this->assertSame(0,$this->pool_balance($this->destination_pool));$this->assertSame(10,(int)$this->batches->find($this->batch_id)['quantity_available_base']);$this->assertNull($this->destination_batch());}
	/** A retry remains idempotent after the source lot was fully depleted. */ public function test_full_transfer_retry_is_idempotent():void{$key='batch-transfer-full:'.wp_generate_uuid4();$this->transfers->transfer($this->batch_id,$this->destination_pool,10,7,'Move all stock',$key);$this->transfers->transfer($this->batch_id,$this->destination_pool,10,7,'Move all stock',$key);$this->assertSame(0,$this->pool_balance($this->source_pool));$this->assertSame(10,$this->pool_balance($this->destination_pool));$this->assertSame('depleted',$this->batches->find($this->batch_id)['status']);global $wpdb;$this->assertSame(1,(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.Schema::table('batches').' WHERE pool_id=%d',$this->destination_pool)));}
	/** Quarantined stock remains unavailable after transfer. */ public function test_quarantine_state_follows_transfer():void{(new BatchOperationsService($this->batches,(new Container())->stock_mutation_service()))->quarantine($this->batch_id,7,'Review');$this->transfers->transfer($this->batch_id,$this->destination_pool,4,7,'Move quarantine','batch-transfer:'.wp_generate_uuid4());$this->assertSame('quarantined',$this->destination_batch()['status']);$this->assertSame(0,apply_filters('laqi_lusm_pool_available_quantity',4,$this->destination_pool));}
	/** Pool balance. */ private function pool_balance(int $pool_id):int{global $wpdb;return(int)$wpdb->get_var($wpdb->prepare('SELECT quantity_base FROM '.Schema::table('pools').' WHERE id=%d',$pool_id));}
	/** Destination batch. @return array<string,mixed>|null */ private function destination_batch():?array{global $wpdb;$row=$wpdb->get_row($wpdb->prepare('SELECT * FROM '.Schema::table('batches').' WHERE pool_id=%d ORDER BY id DESC LIMIT 1',$this->destination_pool),ARRAY_A);return is_array($row)?$row:null;}
}
