<?php
/** Premium batch expiry tests. @package LaqiUnitStockManager */
use LaqiUnitStockManager\Container;
use LaqiUnitStockManager\Domain\Quantity;
use LaqiUnitStockManager\Premium\Alerts\AlertChannelRegistry;
use LaqiUnitStockManager\Premium\Alerts\AlertDeliveryRepository;
use LaqiUnitStockManager\Premium\Alerts\EmailAlertChannel;
use LaqiUnitStockManager\Premium\Batches\BatchExpiryEvaluator;
use LaqiUnitStockManager\Premium\Batches\BatchExpirySettings;
use LaqiUnitStockManager\Premium\Batches\BatchOperationsService;
use LaqiUnitStockManager\Premium\Batches\BatchRepository;
use LaqiUnitStockManager\Storage\Schema;
/** Verifies expiry reporting, deduplicated alerts, and waste movements. */
class Test_Batch_Expiry extends WP_UnitTestCase {
	/** @var int */private $pool_id;/** @var int */private $batch_id;/** @var string */private $lot;/** @var BatchRepository */private $batches;/** @var BatchExpirySettings */private $settings;/** @var BatchExpiryEvaluator */private $evaluator;/** @var BatchOperationsService */private $operations;
	/** Fixture. */public function set_up():void{parent::set_up();global $wpdb;$container=new Container();$this->batches=new BatchRepository($wpdb);$this->settings=new BatchExpirySettings();$channels=new AlertChannelRegistry();$channels->register(new EmailAlertChannel());$deliveries=new AlertDeliveryRepository($wpdb);$deliveries->install();$this->evaluator=new BatchExpiryEvaluator($this->batches,$this->settings,$container->quantity_formatter(),$channels,$deliveries);$mutations=$container->stock_mutation_service();$this->operations=new BatchOperationsService($this->batches,$mutations);$this->lot='EXP-'.wp_generate_uuid4();$this->pool_id=$container->pool_repository()->create('Expiry '.wp_generate_uuid4(),new Quantity('count',0),'unit','unit')->id();$movement=$mutations->apply($this->pool_id,5,'supplier_receipt','expiry:'.wp_generate_uuid4());$this->batch_id=$this->batches->record_receipt($this->pool_id,0,$movement->movement_id(),5,$this->lot,gmdate('Y-m-d',time()+5*DAY_IN_SECONDS));$this->settings->save(7,array('ops@example.com'));}
	/** Cleanup. */public function tear_down():void{global $wpdb;$wpdb->delete(Schema::table('alert_deliveries'),array('pool_id'=>$this->pool_id),array('%d'));$wpdb->delete(Schema::table('batch_allocations'),array('pool_id'=>$this->pool_id),array('%d'));$wpdb->delete(Schema::table('batches'),array('pool_id'=>$this->pool_id),array('%d'));$wpdb->delete(Schema::table('movements'),array('pool_id'=>$this->pool_id),array('%d'));$wpdb->delete(Schema::table('pools'),array('id'=>$this->pool_id),array('%d'));delete_option(BatchExpirySettings::OPTION);wp_clear_scheduled_hook(BatchExpiryEvaluator::CRON_HOOK);parent::tear_down();}
	/** Warning notification is delivered once per batch phase. */public function test_near_expiry_alert_is_deduplicated():void{$sent=0;$lot=$this->lot;$mail=static function($pre,$atts)use(&$sent,$lot):bool{if(false!==strpos($atts['subject'],$lot)){++$sent;}return true;};add_filter('pre_wp_mail',$mail,10,2);try{$this->evaluator->evaluate();$this->evaluator->evaluate();}finally{remove_filter('pre_wp_mail',$mail,10);}$this->assertSame(1,$sent);}
	/** Expiry creates a second alert phase without repeating either phase. */public function test_expired_alert_is_separate_and_deduplicated():void{global $wpdb;$sent=0;$lot=$this->lot;$mail=static function($pre,$atts)use(&$sent,$lot):bool{if(false!==strpos($atts['subject'],$lot)){++$sent;}return true;};add_filter('pre_wp_mail',$mail,10,2);try{$this->evaluator->evaluate();$wpdb->update(Schema::table('batches'),array('expiry_date'=>gmdate('Y-m-d',time()-DAY_IN_SECONDS)),array('id'=>$this->batch_id),array('%s'),array('%d'));$this->evaluator->evaluate();$this->evaluator->evaluate();}finally{remove_filter('pre_wp_mail',$mail,10);}$this->assertSame(2,$sent);}
	/** Daily evaluation is scheduled once and can be removed. */public function test_expiry_evaluator_schedule_lifecycle():void{$this->evaluator->schedule();$first=wp_next_scheduled(BatchExpiryEvaluator::CRON_HOOK);$this->evaluator->schedule();$this->assertSame($first,wp_next_scheduled(BatchExpiryEvaluator::CRON_HOOK));$this->evaluator->unschedule();$this->assertFalse(wp_next_scheduled(BatchExpiryEvaluator::CRON_HOOK));}
	/** Expired write-off uses the dedicated auditable waste type. */public function test_expiry_waste_reconciles_batch_and_pool():void{global $wpdb;$this->operations->write_off($this->batch_id,7,'loss_expiry','Expired batch waste');$this->assertSame(0,(int)$this->batches->find($this->batch_id)['quantity_available_base']);$this->assertSame('loss_expiry',$wpdb->get_var($wpdb->prepare('SELECT type FROM '.Schema::table('movements').' WHERE pool_id=%d ORDER BY id DESC LIMIT 1',$this->pool_id)));$this->assertSame('Expired batch waste',$wpdb->get_var($wpdb->prepare('SELECT reason FROM '.Schema::table('movements').' WHERE pool_id=%d ORDER BY id DESC LIMIT 1',$this->pool_id)));}
	/** Warning window query excludes this later lot until it enters the window. */public function test_expiring_report_respects_window():void{$this->assertContains($this->batch_id,array_map('intval',array_column($this->batches->expiring(7),'id')));$this->assertNotContains($this->batch_id,array_map('intval',array_column($this->batches->expiring(2),'id')));}
}
